[package]
name = "swhkd"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.11.3"
glob = "0.3.0"
tokio = { version = "1.15.0", features = ["full"] }

[[bin]]
name = "swhkd"
path = "src/main.rs"
