[package]
name = "Simple-Wayland-HotKey-Daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.11.3"
glob = "0.3.0"
log = "0.4.0"
env_logger = "0.8.4"
nix = "0.23.1"
clap = "3.0.4"

tokio = { version = "1.15.0", features = ["full"] }

[[bin]]
name = "swhkd"
path = "src/main.rs"
