name: Build Swhkd

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Version tag.
        run: echo "VERSION=$(grep -E '^version' ./Cargo.toml| sed 's/version = \"\(.*\)\"/\1/g')">>$GITHUB_ENV
        
      - name: Setup.
        run: make setup

      - name: ZIP.
        run: ./release.sh
        
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: "Swhkd ${{ env.VERSION }}"
          files: |
            "glibc-x86_64-${{ env.VERSION }}.zip"
            "musl_libc-x86_64-${{ env.VERSION }}.zip"
